//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WedsiteBanHang.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public string Category { get; set; }
        public string ShortDes { get; set; }
        public string FullDexciption { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PiceDiscount { get; set; }
        public Nullable<int> Typeld { get; set; }
        public string Slug { get; set; }
        public Nullable<int> BrandId { get; set; }
    }
}
